# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.CharField(max_length=20)),
                ('band', models.CharField(max_length=20)),
                ('success', models.PositiveIntegerField(default=0)),
                ('fails', models.PositiveIntegerField(default=0)),
                ('start_day', models.DateTimeField(blank=True, null=True)),
                ('end_day', models.DateTimeField(blank=True, null=True)),
                ('clicks', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
