# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='clicks',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='fails',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('p', 'In progress'), ('n', 'Not started'), ('d', 'Done')], default='n', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='success',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
